//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSettings/PauseActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PauseActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PauseActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PauseActions"",
    ""maps"": [
        {
            ""name"": ""PauseAction"",
            ""id"": ""829ca861-341b-48d5-8e87-49281f2ce13b"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""ba29a5d0-7ed4-47f3-83d0-b325aea7b94e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e63a63ba-ee0c-4f59-8d4b-2ddc68ec840f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PauseAction
        m_PauseAction = asset.FindActionMap("PauseAction", throwIfNotFound: true);
        m_PauseAction_Pause = m_PauseAction.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PauseAction
    private readonly InputActionMap m_PauseAction;
    private List<IPauseActionActions> m_PauseActionActionsCallbackInterfaces = new List<IPauseActionActions>();
    private readonly InputAction m_PauseAction_Pause;
    public struct PauseActionActions
    {
        private @PauseActions m_Wrapper;
        public PauseActionActions(@PauseActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_PauseAction_Pause;
        public InputActionMap Get() { return m_Wrapper.m_PauseAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseActionActions set) { return set.Get(); }
        public void AddCallbacks(IPauseActionActions instance)
        {
            if (instance == null || m_Wrapper.m_PauseActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PauseActionActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IPauseActionActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IPauseActionActions instance)
        {
            if (m_Wrapper.m_PauseActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPauseActionActions instance)
        {
            foreach (var item in m_Wrapper.m_PauseActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PauseActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PauseActionActions @PauseAction => new PauseActionActions(this);
    public interface IPauseActionActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
